name: sample-react
services:
- build_command: yarn build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: logosrhema01/careerwheel-ssr
  name: careerwheel-ssr
